import React from "react";
import { TrendingUp, ArrowUpRight } from "lucide-react";

interface StatItem {
  title: string;
  value: string;
  trend?: string;
  description?: string;
}

const stats: StatItem[] = [
  { title: "Revenue Generated by LUSI", value: "$48,240", trend: "+18%" },
  {
    title: "Estimated Revenue Lost Without LUSI",
    value: "$12,300",
    description: "Recovered this month",
  },
  { title: "Total leads", value: "3,482", trend: "+10%" },
  { title: "Qualified leads", value: "2,104", trend: "+1.8%" },
  { title: "Converted leads", value: "2,104", trend: "+10%" },
  { title: "Conversion Rate", value: "24.3%", trend: "+3.2%" },
];

const StatCard = ({ item }: { item: StatItem }) => {
  return (
    <div className="bg-[#121417] border border-white/5 rounded-2xl p-6 flex flex-col justify-between min-h-45 transition-all hover:bg-[#1a1d21]">
      <div>
        <h3 className="text-gray-400 text-sm font-medium mb-4">{item.title}</h3>
        <p className="text-white text-4xl font-semibold tracking-tight leading-none">
          {item.value}
        </p>
      </div>

      <div className="mt-6">
        {item.trend ? (
          <div className="flex items-center gap-2 text-emerald-400 font-medium">
            <TrendingUp size={20} />
            <span>{item.trend}</span>
          </div>
        ) : (
          <p className="text-gray-400 text-sm">{item.description}</p>
        )}
      </div>
    </div>
  );
};

export default function StatsDashboard() {
  return (
    <div>
      <div className="mb-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {stats.map((stat, index) => (
            <StatCard key={index} item={stat} />
          ))}
        </div>
      </div>
    </div>
  );
}
